name: Deploy to GitHub Pages

on:
  # Triggas vid push till main branch
  push:
    branches: [ main ]
  
  # Tillåt manuell triggning från Actions tab
  workflow_dispatch:

# Ger GITHUB_TOKEN de rättigheter som behövs för att deployjera till Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Tillåt endast en samtidig deployment, hoppar över runs som är köade mellan den pågående och senaste köade.
# Avbryt dock inte pågående runs eftersom vi vill låta dessa productiondeployments slutföras.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Byggjobb
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install dependencies
        run: bun install --frozen-lockfile
        
      - name: Build with Vite
        run: bun run build
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deploymentjobb
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4